### ISSUE TITLE
1.20.1 炸服后online仍然为1导致无法进服

### ISSUE THREAD

**Issue by THYuyukoZLAK** [mlus-asuka/PlayerSync#16]
服务器崩溃时如果有玩家在线对应玩家的 online 值仍然为1，重启后模组判定玩家在线而踢出  
使用`/stop`关闭服务器有同样问题

**Comment by mlus-asuka** [comment]
mysql手动改一下吧。。
```mysql
UPDATE player_data SET online=0;
```

**Comment by THYuyukoZLAK** [comment]
之前是手动改的没错  
不过服务器平时没人值守每次炸了都要改有点麻烦了  
考虑加个启动时自动重设之类的东西吗

**Comment by mlus-asuka** [comment]
已修复。崩服之后加入之前的服务器即可。或者崩服五分钟后可加入其他的服务器。
