### ISSUE TITLE
request for forge 1.18.2

### ISSUE THREAD

**Issue by mocksonline** [mlus-asuka/PlayerSync#2]
Request for forge 1.18.2. I fork it and try to make it runs on 1.18.2, but server crashed with "Exception caught during firing event: com.mysql.cj.jdbc.Driver", I know I cannot take this job.
So if you really have free time, could you do a compatibility mod with forge 1.18.2? Like you said on web https://www.mcmod.cn/class/8461.html :)

**Comment by mocksonline** [comment]
没事了，我的mysql连接器坏了 : p

**Comment by mlus-asuka** [comment]
你自己编译的话需要自己额外提供一个jdbc驱动类包才能用。
