### ISSUE TITLE
need help 1.20.1 proxy server

### ISSUE THREAD

**Issue by KwonGiYoig** [mlus-asuka/PlayerSync#20]
I want to use this mod on the 1.20.1 proxy server.
After installing this mod, modifying the config file, and running the server was successful,
But, when I try to download this mod on the client and access the server, the crash pops up.
Is there a solution?
I attach the config file I wrote below.

[general]
	#The host of the database
	host = "localhost"
	#database port
	#Range: 0 ~ 65535
	db_port = 3306
	#whether use SSL
	use_ssl = false
	#username
	user_name = "root"
	#password
	password = "1234"
	#the server id should be unique
	Server_id = 45456457
	#The worlds that will be synchronized.If running in server it is supposed to have only one
	sync_world = ["world"]
	#Whether synchronize chat
	sync_chat = true

**Comment by mlus-asuka** [comment]
you don't need to install it on cilent
