### ISSUE TITLE
[1.20.1] 副手物品未同步

### ISSUE THREAD

**Issue by BredyAK** [mlus-asuka/PlayerSync#25]
目前的问题是副手物品未同步，物品会留在原服务器。由此猜测光标物品（玩家选择了一个物品，此时物品漂浮在屏幕上时即为光标物品）也没有同步，希望作者可以兼顾一下。

**Comment by mlus-asuka** [comment]
https://github.com/mlus-asuka/PlayerSync/actions/runs/11286841412
已更新
