### ISSUE TITLE
Request for forge-1.12.2-14.23.5.2860

### ISSUE THREAD

**Issue by Jenzoga** [mlus-asuka/PlayerSync#28]
Hi,

May i ask if you can port PlayerSync to forge-1.12.2-14.23.5.2860 ( https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-installer.jar )

I trying to run RL Craft Degora with 15+ people but it seem impossible as it is lag so bad . So I looking for let player form a group and adventure out to different server with PlayerSync.

Thank you in advance.

**Comment by mlus-asuka** [comment]
quite busy this year

**Comment by Jenzoga** [comment]
no worries. thank for reply.
