### ISSUE TITLE
Forge1.19.2安装此mod后服务器无法启动

### ISSUE THREAD

**Issue by KelvinZhang512** [mlus-asuka/PlayerSync#4]
服务端版本：Forge43.2.14，mod下载于https://www.mcmod.cn/download/8461.html的1.1.3版本，装上并配置完毕后服务器启动失败。
附上服务器日志：
[ConsoleLog.txt](https://github.com/mlus-asuka/PlayerSync/files/12223745/ConsoleLog.txt)
[CrashReport.txt](https://github.com/mlus-asuka/PlayerSync/files/12223746/CrashReport.txt)

**Comment by mlus-asuka** [comment]
你的MySQL服务器没有响应。确认一下有没有配置好。

**Comment by KelvinZhang512** [comment]
> 你的MySQL服务器没有响应。确认一下有没有配置好。

问题已解决，是我在mod配置文件playersync-common.toml内的”sync_world = []“的中括号内填入了服务器地图文件夹名（server.properties内的level-name）导致的无法启动。

**Comment by KelvinZhang512** [comment]
就在我刚发完上一条消息过后不久服务器又崩了，mclo.gs无法解析错误原因，控制台输出和错误报告已附上。
[ConsoleLog.txt](https://github.com/mlus-asuka/PlayerSync/files/12225604/ConsoleLog.txt)
[CrashReport.txt](https://github.com/mlus-asuka/PlayerSync/files/12225605/CrashReport.txt)

**Comment by mlus-asuka** [comment]
没看出跟playersync有什么关系。建议先把java进程全关了，重启一遍mysql服务器，再重启服务器试试。

**Comment by KelvinZhang512** [comment]
问题已解决，是我的MySQL用户名和安装系统时创建的用户名相同而使MySQL报连接数过多，更改成一个不一样的用户名即可（虽然我并不清楚其中的运作原理但是这样改了确实没问题了）。
