### ISSUE TITLE
你在curseforge

### ISSUE THREAD

**Issue by HiBer2007** [mlus-asuka/PlayerSync#5]
你在curseforge上的发行版本填错版本号了，那是1.19.2的模组

**Comment by mlus-asuka** [comment]
我发现了。新版本还在测试，等一下吧

**Comment by HiBer2007** [comment]
此外，mcmod上的下载链接已经消失

**Comment by mlus-asuka** [comment]
> 此外，mcmod上的下载链接已经消失

有bug。我删掉了(

**Comment by HiBer2007** [comment]
现在需要1.18.2的版本，请问我可以从哪里下载

**Comment by HiBer2007** [comment]
建议把curseforge上的也删掉，撞到服务器里直接爆炸，版本号写错了

**Comment by mlus-asuka** [comment]
qq:1319237806




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mlus-asuka/PlayerSync"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月4日(星期五) 中午11:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mlus-asuka/PlayerSync] 你在curseforge (Issue #5)





 
现在需要1.18.2的版本，请问我可以从哪里下载

**Comment by HiBer2007** [comment]
额考不考虑用fast.uc.cn

**Comment by HiBer2007** [comment]
我现在手机不在手上

**Comment by mlus-asuka** [comment]
不是。是现在还没测试完。不好正式发布

**Comment by HiBer2007** [comment]
用fast.uc.cn，设置1天的期限，

**Comment by HiBer2007** [comment]
或者等一会我加过去也可以

**Comment by mlus-asuka** [comment]
> 或者等一会我加过去也可以

你等会加我吧。多半是有bug的。。。

**Comment by HiBer2007** [comment]
欧克欧克
我去开个测试服试试，
还有，关于模组兼容性，背包内的不同模组的物品和盔甲是可以同步的ba

**Comment by HiBer2007** [comment]
或者说我一会去试一下

**Comment by mlus-asuka** [comment]
> 欧克欧克 我去开个测试服试试， 还有，关于模组兼容性，背包内的不同模组的物品和盔甲是可以同步的ba

可以

**Comment by HiBer2007** [comment]
考不考虑支持一下postgres sql

**Comment by HiBer2007** [comment]
一样的sql标准

**Comment by mlus-asuka** [comment]
curseforge已更新
